namespace Resources
{
static const char BCI2000_credits[] =
    "BCI2000 Project: a platform for real-time bio-signal research\n"
    "© BCI2000 Team and contributors " PROJECT_TIMESPAN "\n\n"
    "CITATION\n\n"
    "G. Schalk, D.J. McFarland, T. Hinterberger, N. Birbaumer, and J.R. Wolpaw:\r"
    "BCI2000: A General-Purpose Brain-Computer Interface (BCI) System,\r"
    "IEEE Trans Biomed Eng, 51(6), June 2004.\n\n"
    "CORE TEAM\n\n"
    "Project Director\n Peter Brunner, Ph.D.\n\n"
    "Project Coordinator\n James Swift, Ph.D.\n\n"
    "Chief Software Engineer\n Juergen Mellinger, M.E.\n\n"
    "Chief Systems Engineer\n Markus Adamek, M.Sc.\n\n"
    "Software Engineers\n Alexander Belsten, B.Sc.\n William Engelhardt, B.Sc.\n Huiling Huang, M.Sc.\n Nicholas Luzcak, B.Sc.\n Dhruva Mehta, B.Sc.\n\n"
    "Software Testing and Support\n Emily Cohen, B.Sc.\n\n"
    "\nADDITIONAL CONTRIBUTORS\n\n Erik Aarnoutse (UMC Utrecht)\n Brendan Allison (Georgia State)\n Nick Anderson "
    "(Cardinal Health)\n Kosta Andoni (RPI)\n Sean Austin (RPI)\n David Balderas (Tecnologico de Monterrey)\n Bernd "
    "Battes (Max-Planck-Institute Tuebingen)\n Robert Bell (EGI)\n Tim Blakely (University of Washington)\n Maria "
    "Laura Blefari (Scuola Superiore Sant'Anna, Pisa)\n Sam Briskin (Wadsworth)\n Simona "
    "Bufalari (Fondazione Santa Lucia)\n Bob Cardillo\n Rudi Cilibrasi\n William Coon (Wadsworth)\n Febo Cincotti "
    "(Fondazione Santa Lucia)\n George Dimitriadis (Radboud University Nijmegen)\n Nathaniel Elkins (Wadsworth)\n "
    "Jason Farquhar (Max-Planck-Institute Tuebingen; Radboud University Nijmegen)\n Joshua Fialkoff (Wadsworth/RPI)\n "
    "Emanuele Fiorilla (Fondazione Santa Lucia)\n Richmund Fries (RPI)\n Dario Gaetano (University of Sydney)\n Andrew "
    "Geronimo (Pennsylvania State University)\n Gaetano Gargiulo (University of Naples)\n Kaleb Goering (Kansas State "
    "University)\n Christoph Guger (g.tec)\n Shane Guillory (Ripple)\n Fanny Grosselin (Institut du Cerveau et de la "
    "Moelle epiniere - ICM (Brain & Spine Institute))\n Sebastian Halder (University of Tuebingen)\n Masayo Haneda "
    "(Starlab)\n Joerg Hansmann\n Steffen Heimes (Ant Neuro)\n Jeremy Hill (Max-Planck-Institute Tuebingen; "
    "Wadsworth)\n Thilo Hinterberger (University of Tuebingen)\n Jenny Hizver (Wadsworth)\n Sam Inverso (MIT Media Lab "
    "Europe)\n Vaishali Kamat (Cambridge Consultants)\n Stefan Klanke (Donders Center)\n Dean Krusienski (Old Dominion "
    "University)\n Marco Mattiocco (Fondazione Santa Lucia)\n Dennis McFarland (Wadsworth)\n Juergen Mellinger "
    "(University of Tuebingen)\n Griffin Milsap (RPI, Johns Hopkins University)\n Melody M. Moore-Jackson (Georgia "
    "State)\n James Norton (University of Illinois)\n Robert Oostenveld (Donders Center)\n Giulio Pasquariello "
    "(University of Naples)\n Yvan Pearson-Lecours (Cambridge Consultants)\n Cristhian Potes (University of Texas/El "
    "Paso)\n Christian Puzicha (Max-Planck-Institute Tuebingen)\n Giby Raphael (B-Alert)\n Justin Renga (RPI)\n "
    "Alejandro Riera (Starlab)\n Gerwin Schalk (Wadsworth)\n Thomas Schreiner (Max-Planck-Institute Tuebingen)\n "
    "Chintan Shah (Georgia State)\n Sidhant Sharma (Cyberglove Systems)\n Mark Span (University of Groningen)\n David "
    "Steines (University of Illinois)\n George Townsend (Algoma University)\n Chris Veigl (FORTEC)\n Janki Vora "
    "(Georgia State)\n Richard Wang (Wadsworth)\n Adam Wilson (Wadsworth; University of Cincinnati)\n Yang Zhen\n "
    "Matthias Zeintlinger(g.tec)\n Shi Dong Zheng (Georgia State)\n\n\n"
    "CURRENT SPONSOR\n"
    " National Center for Adaptive Neurotechnologies\n"
    " PI: Jonathan Wolpaw\n P41 grant sponsored by NIN-NIBIB (EB018783)\n\n"
    " Peter Brunner, R01 grant sponsored by NIH/NIBIB (EB026439)\n"
    " Peter Brunner, U24 grant sponsored by NIH/NINDS (NS109103)\n\n"
  "PREVIOUS SPONSORS & FOUNDERS\n"
    " Gerwin Schalk, R01 grant sponsored by NIH/NIBIB (EB006356)\n"
    " Jonathan Wolpaw, BRP grant sponsored by NIH/NIBIB/NINDS (EB000856)\n"
    "\n";
static int BCI2000_credits_leadingLines = 3;
static int BCI2000_credits_emptyLineHeight = 5;
} // namespace Resources
